import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Removed Geist_Mono
import "./globals.css";
import Navbar from "./container/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Zerahaans",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-950 text-white`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
